const path = require('path');

const ACTION_TYPES = {
  INITIAL: 'INITIAL',
  LOGIN_APP: 'LOGIN_APP',
  MODIFY_PW: 'MODIFY_PW',
};

const PAGE_TYPES = {
  LOGIN_FORM: 'LOGIN_FORM',
  APP_FORM: 'APP_FORM',
};

const EVENT_TYPES = {
  // DEPRECATED
  SHARE_GLOBAL_DATA: 'SHARE_GLOBAL_DATA',
  MODIFY_GLOBAL_DATA: 'MODIFY_GLOBAL_DATA',
  RENDER_PROCESS_READY: 'RENDER_PROCESS_READY',
  // USEFUL
  PRE_DATA_READY: 'PRE_DATA_READY',
  LOGIN_CLIENT: 'LOGIN_CLIENT',
  CANCEL_LOGIN_CLIENT: 'CANCEL_LOGIN_CLIENT',
  CANCEL_MODIFY_APP: 'CANCEL_MODIFY_APP',
  SHOW_APP_FORM: 'SHOW_APP_FORM',
  SUBMIT_APP_CONFIG: 'SUBMIT_APP_CONFIG',
};

const PROCESS_EVENT_TYPE = {
  EXEC_SCRIPT: 'EXEC_SCRIPT',
};

module.exports.default = module.exports = {
  ACTION: ACTION_TYPES,
  EVENT: EVENT_TYPES,
  PROCESS_EVENT: PROCESS_EVENT_TYPE,
  DB: path.resolve(__dirname, 'yufu.dt'),
  APP_NAME: 'yufu-desktop-client',
  APP_NAME_ZH_CN: '玉符客户端',
  PAGE: PAGE_TYPES,
};
